server: 
  port: 8081
  servlet:
    context-path: /sher
  tomcat:
    uri-encoding: utf-8

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true # 默认值:true
      cluster-nodes: 127.0.0.1:9300 #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
      #cluster-name: elasticsearch #默认值
      #cluster-nodes 集群节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点
      #properties 用来配置客户端的额外属性
      properties:
        path:
          home: /data/project/target/elastic #存储索引的位置
        transport:
          tcp:
            connect_timeout: 120s
        